# Generated by Django 5.1.4 on 2025-02-06 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('max_miembros', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numMaxAutores', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('nombre__in', ['Individual', 'Jubilado', 'Estudiante', 'Familiar'])), name='ch_plan_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('numReproducciones', models.IntegerField()),
                ('urlDrive', models.CharField(max_length=200)),
                ('autores', models.ManyToManyField(to='virgenDB.autor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgenDB.programa')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='programa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.programa'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_de_baja', models.DateField(blank=True, null=True)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.familia')),
                ('me_gusta_podcast', models.ManyToManyField(blank=True, related_name='fk_user_podcast_liked', to='virgenDB.podcast')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgenDB.plan')),
                ('podcast_pendientes', models.ManyToManyField(blank=True, related_name='fk_user_podcast_pend', to='virgenDB.podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numReproducciones', models.IntegerField()),
                ('idPodcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgenDB.podcast')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virgenDB.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='podcast',
            constraint=models.CheckConstraint(condition=models.Q(('categoria__in', ['Educativo', 'Comedia', 'Formacion'])), name='ch_categoria'),
        ),
    ]
