# Generated by Django 5.1.4 on 2025-02-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgenDB', '0002_usuario_fecha_de_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodos_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pago_con_tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.IntegerField()),
                ('cvc', models.IntegerField(default=3)),
                ('nombre_completo', models.CharField(max_length=40)),
                ('predeterminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_electronico', models.CharField(max_length=40)),
                ('predeterminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia_bancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('nombre_cuenta', models.CharField(max_length=100)),
                ('predeterminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='metodos_pago',
            field=models.ManyToManyField(blank=True, related_name='fk_user_metodo_pago', to='virgenDB.metodos_pago'),
        ),
        migrations.AddField(
            model_name='metodos_pago',
            name='pago_con_tarjeta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.pago_con_tarjeta'),
        ),
        migrations.AddField(
            model_name='metodos_pago',
            name='paypal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.paypal'),
        ),
        migrations.AddField(
            model_name='metodos_pago',
            name='transferencia_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.transferencia_bancaria'),
        ),
    ]
