# Generated by Django 5.1.4 on 2025-02-21 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgenDB', '0003_metodos_pago_pago_con_tarjeta_paypal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='metodos_pago',
        ),
        migrations.AddField(
            model_name='metodos_pago',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='virgenDB.usuario'),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='predeterminado',
            field=models.BooleanField(default=True),
        ),
    ]
