# Generated by Django 5.1.4 on 2025-02-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virgenDB', '0005_alter_pago_con_tarjeta_predeterminado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_con_tarjeta',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='predeterminado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transferencia_bancaria',
            name='predeterminado',
            field=models.BooleanField(default=False),
        ),
    ]
